<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GameDirectory>$(GITHUB_WORKSPACE)/Refs</GameDirectory>
    </PropertyGroup>

    <Import Project="LipSync.csproj.user" Condition="Exists('LipSync.csproj.user')" />

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <EnableFrameworkPathOverride>true</EnableFrameworkPathOverride>
        <FrameworkPathOverride>$(GameDirectory)\Beat Saber_Data\Managed</FrameworkPathOverride>
        <MarkPackageReferencesAsExternallyResolved>false</MarkPackageReferencesAsExternallyResolved>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BeatSaberModdingTools.Tasks" Version="2.0.0-beta7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.23.2"
            GeneratePathProperty="true" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="UI\Settings.bsml" />
        <EmbeddedResource Include="..\model\model.onnx" RelativePath="model.onnx" />
        <EmbeddedResource Include="..\model\config.json" RelativePath="config.json" />
    </ItemGroup>

    <ItemGroup>
        <None Include="LipSync.csproj.user" Condition="Exists('LipSync.csproj.user')" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\OpenLipSync.Inference\**\*.cs"
            Link="OpenLipSync\%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="System.Memory">
            <Aliases>SystemMemory</Aliases>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="BeatSaber.ViewSystem">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\BeatSaber.ViewSystem.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="BSML">
            <HintPath>$(GameDirectory)\Plugins\BSML.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Hive.Versioning">
            <HintPath>$(GameDirectory)\Libs\Hive.Versioning.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="IPA.Loader">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\IPA.Loader.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Main">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Main.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="mscorlib" />
        <Reference Include="netstandard" />
        <Reference Include="System" />
        <Reference Include="System.Core" />
        <Reference Include="System.Xml.Linq" />
        <Reference Include="System.Data.DataSetExtensions" />
        <Reference Include="System.Data" />
        <Reference Include="System.Xml" />
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Unity.TextMeshPro.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UIElementsModule">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.UIModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(GameDirectory)\Libs\Newtonsoft.Json.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="CustomAvatar">
            <HintPath>$(GameDirectory)\Plugins\CustomAvatar.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

</Project>